spring:
  application:
    name: customer_experience

  # config de DB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # config rabbitmq
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    # Para conexion externa
    template:
      retry:
        enabled: true
        initial-interval: 5s

  # Mailtrap
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    secret: ${JWT_SECRET}
#    expiration: ${JWT_EXPIRATION}

# config espocmr
espocrm:
  base-url: ${ESPOCRM_BASE_URL}
  api-key: ${ESPOCRM_API_KEY}
