spring:
  application:
    name: customer_experience

  # config de DB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:  | 
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # config rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # --- LO NUEVO PARA EL EMAIL ---
    mail:
        host: sandbox.smtp.mailtrap.io
        port: 2525
        username: 5649306d0bdd38
        password: bb1bc53d4d456a
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true

    # --- PARA QUE LEA BIEN LAS FECHAS DEL GRUPO A ---
    jackson:
        serialization:
          write-dates-as-timestamps: false

  jwt:
    secret: ${JWT_SECRET}
#    expiration: ${JWT_EXPIRATION}

# config espocmr
espocrm:
  base-url: ${ESPOCRM_BASE_URL}
  api-key: ${ESPOCRM_API_KEY}
